# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: My's Blog
description: A potato-loving programmer who accumulates his own knowledge, builds his own knowledge systems, and shares technical blog posts.
author: TDou
language: zh-CN
timezone: Asia/Shanghai
favicon: https://assets-cdn.github.com/favicon.ico

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://tdou.cc
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year:month:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: TDOU.CC
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: replica
Plugins:
  - hexo-generator-cname

# Google Analytics
ga: UA-145423637-1 # GA code UA-XXXXXXXX-X

#marked setting for markdown
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

gcs: 013515171728354998330:ocbdx7u5sus # GOOGLE CUSTOM SEARCH
baidutongji: dc1607e81c6038df0ef945fb4e9e0476 # BAIDU TONGJI CODE
disqus: tdou # DISQUS ID
baidu_push: true

location: Beijing, Chine 
email: kevin@kylin.app
baidusitemap: 
path: baidusitemap.xml


avatar: https://tdou.cc/images/avatar.jpg
social:
  github: https://github.com/CnTDou
  weibo: https://www.weibo.com/5730394625
  csdn: https://me.csdn.net/gjmvvv
  cnblogs: http://www.cnblogs.com/GJM6/
  jianshu: https://www.jianshu.com/u/b1503830fe57
  zhihu: https://www.zhihu.com/people/CnTDou
  twitter: https://twitter.com/CnTDou
  facebook: https://www.facebook.com/CnTDou

footer:
  custom_name: Kylin-Technologies
  custom_url: https://github.com/KylinTechnologies

# flagcounter
flagcounter_href: https://info.flagcounter.com/UVrV
flagcounter_img_src: https://s01.flagcounter.com/count/UVrV/bg_FFFFFF/txt_000000/border_CCCCCC/columns_5/maxflags_15/viewers_0/labels_1/pageviews_0/flags_0/percent_0/

deploy:
  type: git
  repo: git@github.com:CnTDou/kylin.app.git
  branch: gh-pages
