# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: TDou's Blog
description: This world is my canteen, and I get nutrition from it to enrich myself. Constant holding can make me  a progressive.
author: TDou
language: zh-CN
timezone: Asia/Shanghai
favicon: https://assets-cdn.github.com/favicon.ico

# 更改链接结果形式 https://hexo.io/zh-cn/docs/permalinks
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://tdou.cc
root: /
permalink: :lang/:abbrlink.html
permalink_defaults:
  lang: cn
  iscopyright: true
  comments: true
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32
  rep: dec    # 进制：dec(default) and hex

layout: post

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :lang/:year:month:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
isplay_updated: true
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: TDOU.CC
category_map:
  编程: programming
  生活: life
  其他: other
  搭建博客: blog
tag_map:
  编程: programming
  生活: life
  其他: other
  
  
# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 0
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: replica
Plugins:
  - hexo-generator-cname

# Google Analytics
ga: UA-145423637-1 # GA code UA-XXXXXXXX-X

#marked setting for markdown
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: true
  smartLists: true
  smartypants: true

gcs: 013515171728354998330:ocbdx7u5sus # GOOGLE CUSTOM SEARCH
baidutongji: dc1607e81c6038df0ef945fb4e9e0476 # BAIDU TONGJI CODE
disqus: tdou # DISQUS ID
baidu_push: true

location: Beijing, China 
email: kevin@kylin.app
baidusitemap: 
path: baidusitemap.xml

search:
  path: search.xml
  field: post
  format: html
  limit: 10000

local_search:
  enable: true

# 打赏
donate: 
  enable: true
  message: 欣赏此文？求鼓励，求支持！
  btc: 3JfBFrELvdXNVVhT2MXvkZNsQAuy12WfDR
  btc_url: http://img.0x96m.com/btc.jpg
  ali_url: http://img.0x96m.com/pay_ali.jpg
  wechat_url: http://img.0x96m.com/pay_wx.jpg

avatar: http://img.0x96m.com/avatar.jpg
social:
  github: https://github.com/T-Dou
  weibo: https://www.weibo.com/5730394625
  csdn: https://me.csdn.net/gjmvvv
  cnblogs: http://www.cnblogs.com/TDou
  jianshu: https://www.jianshu.com/u/b1503830fe57
  zhihu: https://www.zhihu.com/people/CnTDou
  twitter: https://twitter.com/CnTDou
  facebook: https://www.facebook.com/CnTDou

footer:
  custom_name: Kylin-Technologies
  custom_url: https://github.com/KylinTechnologies

# flagcounter
flagcounter_href: https://info.flagcounter.com/UVrV
flagcounter_img_src: https://s01.flagcounter.com/count/UVrV/bg_FFFFFF/txt_000000/border_CCCCCC/columns_5/maxflags_15/viewers_0/labels_1/pageviews_0/flags_0/percent_0/

#deploy:
#  type: git
#  repo: git@github.com:CnTDou/kylin.app.git
#  branch: gh-pages
